import {
  ActivityStatus,
  ActivityType,
  ContractStatus,
  OpportunityStage,
  ProposalStatus,
  type ISalesData,
  type ITeamMember,
} from "./salesTypes";

const TEAM_MEMBER_SEEDS = [
  ["tm01", "Ava Mokoena", "Pipeline Director", 68, "Johannesburg", ["Enterprise", "SaaS"]],
  ["tm02", "Lebo Dlamini", "Account Executive", 74, "Johannesburg", ["Healthcare", "Renewals"]],
  ["tm03", "Siya Daniels", "Account Executive", 62, "Cape Town", ["Retail", "Analytics"]],
  ["tm04", "Nomsa Khumalo", "Client Success Lead", 58, "Durban", ["Renewals", "Onboarding"]],
  ["tm05", "Thando Naidoo", "Sales Consultant", 81, "Johannesburg", ["Manufacturing", "Cloud"]],
  ["tm06", "Ayanda Peters", "Sales Consultant", 76, "Cape Town", ["Education", "SMB"]],
  ["tm07", "Kamo Maseko", "Business Development Rep", 84, "Pretoria", ["Outbound", "Prospecting"]],
  ["tm08", "Kea Mhlongo", "Business Development Rep", 79, "Johannesburg", ["Inbound", "Lead Qualification"]],
  ["tm09", "Naledi Venter", "Sales Operations Analyst", 57, "Cape Town", ["Reporting", "Automation"]],
  ["tm10", "Sibusiso Meyer", "Deal Desk Specialist", 66, "Pretoria", ["Pricing", "Contracts"]],
  ["tm11", "Reabetswe Ncube", "Account Executive", 69, "Johannesburg", ["Enterprise", "Banking"]],
  ["tm12", "Tumi Jacobs", "Account Executive", 61, "Cape Town", ["Public Sector", "RFP"]],
  ["tm13", "Mpho Mokoena", "Sales Consultant", 73, "Durban", ["Logistics", "Field Sales"]],
  ["tm14", "Claire Mabuza", "Sales Consultant", 77, "Johannesburg", ["Technology", "Cloud"]],
  ["tm15", "Brian Sithole", "Client Success Manager", 64, "Pretoria", ["Retention", "Renewals"]],
  ["tm16", "Rethabile Madonsela", "Client Success Manager", 71, "Cape Town", ["Implementation", "Upsell"]],
  ["tm17", "Anika Pillay", "Business Development Rep", 83, "Durban", ["Prospecting", "Healthcare"]],
  ["tm18", "Tebogo Masebe", "Business Development Rep", 80, "Johannesburg", ["Prospecting", "Technology"]],
  ["tm19", "Zinhle Dube", "Proposal Manager", 59, "Cape Town", ["Proposals", "RFP"]],
  ["tm20", "Jason Molefe", "Proposal Manager", 63, "Johannesburg", ["Proposals", "Renewals"]],
  ["tm21", "Palesa Ntuli", "Sales Analyst", 72, "Pretoria", ["Forecasting", "Insights"]],
  ["tm22", "Nadine Fourie", "Sales Analyst", 75, "Cape Town", ["Dashboards", "Pipeline"]],
  ["tm23", "Tshepo Ndlovu", "Account Executive", 67, "Johannesburg", ["Mining", "Enterprise"]],
  ["tm24", "Karabo Cele", "Account Executive", 70, "Durban", ["Logistics", "Mid-Market"]],
  ["tm25", "Ruan Govender", "Sales Consultant", 78, "Pretoria", ["Services", "Negotiation"]],
  ["tm26", "Minenhle Hlongwane", "Sales Consultant", 82, "Johannesburg", ["Insurance", "Outbound"]],
  ["tm27", "Yolanda Coetzee", "Client Success Lead", 60, "Cape Town", ["Renewals", "Risk"]],
  ["tm28", "Refilwe Zuma", "Business Development Rep", 85, "Johannesburg", ["Pipeline Creation", "Discovery"]],
  ["tm29", "Neo van der Merwe", "Deal Desk Specialist", 65, "Durban", ["Contracts", "Commercial"]],
  ["tm30", "Asanda Gcaba", "Sales Operations Analyst", 74, "Cape Town", ["Automation", "Capacity Planning"]],
] as const;

export const MOCK_TEAM_MEMBERS: ITeamMember[] = TEAM_MEMBER_SEEDS.map(
  ([id, name, role, availabilityPercent, region, skills]) => ({
    availabilityPercent,
    id,
    name,
    region,
    role,
    skills: [...skills],
  }),
);

export const INITIAL_SALES_DATA: ISalesData = {
  opportunities: [
    {
      id: "opp-1",
      title: "Boxfusion renewal expansion",
      name: "Boxfusion renewal expansion",
      clientId: "c1",
      contactId: "cont1",
      ownerId: "tm02",
      estimatedValue: 1850000,
      value: 1850000,
      currency: "ZAR",
      stage: OpportunityStage.Negotiating,
      source: 3,
      probability: 82,
      expectedCloseDate: "2026-04-30",
      createdDate: "2026-02-14",
      nextStep: "Finalize commercial concessions with procurement.",
      description: "Upsell analytics and managed services into the annual renewal.",
    },
    {
      id: "opp-2",
      title: "Nexa Health rollout",
      name: "Nexa Health rollout",
      clientId: "c2",
      contactId: "cont2",
      ownerId: "tm19",
      estimatedValue: 1320000,
      value: 1320000,
      currency: "ZAR",
      stage: OpportunityStage.ProposalSent,
      source: 1,
      probability: 68,
      expectedCloseDate: "2026-05-06",
      createdDate: "2026-03-01",
      nextStep: "Clarify onboarding timeline and hosting scope.",
      description: "Regional healthcare deployment covering four hospitals.",
    },
    {
      id: "opp-3",
      title: "Umoya Logistics automation",
      name: "Umoya Logistics automation",
      clientId: "c3",
      contactId: "cont3",
      ownerId: "tm24",
      estimatedValue: 910000,
      value: 910000,
      currency: "ZAR",
      stage: OpportunityStage.Qualified,
      source: 2,
      probability: 51,
      expectedCloseDate: "2026-05-12",
      createdDate: "2026-03-18",
      nextStep: "Run discovery workshop with operations team.",
      description: "Workflow automation and reporting for route planning.",
    },
    {
      id: "opp-4",
      title: "Lattice Retail renewal",
      name: "Lattice Retail renewal",
      clientId: "c4",
      contactId: "cont4",
      ownerId: "tm27",
      estimatedValue: 740000,
      value: 740000,
      currency: "ZAR",
      stage: OpportunityStage.Negotiating,
      source: 3,
      probability: 76,
      expectedCloseDate: "2026-04-29",
      createdDate: "2026-02-22",
      nextStep: "Lock down support SLA and card-processing addendum.",
      description: "Renewal with branch rollout add-on.",
    },
    {
      id: "opp-5",
      title: "CrestBank data platform",
      name: "CrestBank data platform",
      clientId: "c5",
      contactId: "cont5",
      ownerId: "tm11",
      estimatedValue: 2250000,
      value: 2250000,
      currency: "ZAR",
      stage: OpportunityStage.New,
      source: 1,
      probability: 42,
      expectedCloseDate: "2026-05-22",
      createdDate: "2026-04-04",
      nextStep: "Confirm steering committee attendees for discovery.",
      description: "Enterprise data and reporting platform modernization.",
    },
    {
      id: "opp-6",
      title: "Marula Services contract rescue",
      name: "Marula Services contract rescue",
      clientId: "c6",
      contactId: "cont6",
      ownerId: "tm29",
      estimatedValue: 560000,
      value: 560000,
      currency: "ZAR",
      stage: OpportunityStage.ProposalSent,
      source: 2,
      probability: 63,
      expectedCloseDate: "2026-05-02",
      createdDate: "2026-03-09",
      nextStep: "Re-issue revised commercial schedule.",
      description: "At-risk contract that needs fast legal turnaround.",
    },
  ],
  proposals: [
    { id: "prop-1", opportunityId: "opp-1", clientId: "c1", title: "Boxfusion renewal commercial pack", currency: "ZAR", validUntil: "2026-04-30", status: ProposalStatus.Submitted, value: 1850000 },
    { id: "prop-2", opportunityId: "opp-2", clientId: "c2", title: "Nexa Health implementation proposal", currency: "ZAR", validUntil: "2026-05-06", status: ProposalStatus.Submitted, value: 1320000 },
    { id: "prop-3", opportunityId: "opp-3", clientId: "c3", title: "Umoya discovery scope", currency: "ZAR", validUntil: "2026-05-14", status: ProposalStatus.Draft, value: 910000 },
    { id: "prop-4", opportunityId: "opp-4", clientId: "c4", title: "Lattice Retail renewal pack", currency: "ZAR", validUntil: "2026-04-29", status: ProposalStatus.Approved, value: 740000 },
  ],
  renewals: [
    { id: "ren-1", contractId: "ct1", status: ActivityStatus.Scheduled, clientName: "Boxfusion", renewalDate: "2026-04-30", value: 1850000, daysUntilRenewal: 4 },
    { id: "ren-2", contractId: "ct2", status: ActivityStatus.Scheduled, clientName: "Lattice Retail", renewalDate: "2026-05-07", value: 740000, daysUntilRenewal: 11 },
    { id: "ren-3", contractId: "ct3", status: ActivityStatus.Scheduled, clientName: "Marula Services", renewalDate: "2026-05-15", value: 560000, daysUntilRenewal: 19 },
  ],
  activities: [
    { id: "act-1", type: ActivityType.Call, subject: "Confirm renewal concessions", title: "Confirm renewal concessions", description: "Call procurement at Boxfusion to settle renewal discount bands.", priority: 1, dueDate: "2026-04-28", assignedToId: "tm02", assignedToName: "Lebo Dlamini", relatedToType: 2, relatedToId: "opp-1", status: ActivityStatus.Scheduled, completed: false },
    { id: "act-2", type: ActivityType.Email, subject: "Send onboarding assumptions", title: "Send onboarding assumptions", description: "Email Nexa Health with final onboarding assumptions and dependencies.", priority: 1, dueDate: "2026-04-29", assignedToId: "tm19", assignedToName: "Zinhle Dube", relatedToType: 2, relatedToId: "opp-2", status: ActivityStatus.Scheduled, completed: false },
    { id: "act-3", type: ActivityType.Meeting, subject: "Operations discovery workshop", title: "Operations discovery workshop", description: "Walk Umoya through reporting and route-optimization workflows.", priority: 2, dueDate: "2026-05-01", assignedToId: "tm24", assignedToName: "Karabo Cele", relatedToType: 2, relatedToId: "opp-3", status: ActivityStatus.Scheduled, completed: false },
    { id: "act-4", type: ActivityType.Task, subject: "Resend revised legal schedule", title: "Resend revised legal schedule", description: "Update Marula Services with revised commercial schedule and risk notes.", priority: 1, dueDate: "2026-04-27", assignedToId: "tm29", assignedToName: "Neo van der Merwe", relatedToType: 2, relatedToId: "opp-6", status: ActivityStatus.Scheduled, completed: false },
  ],
  contracts: [
    { id: "ct1", clientId: "c1", opportunityId: "opp-1", title: "Boxfusion annual managed services agreement", contractValue: 1850000, currency: "ZAR", startDate: "2026-01-01", endDate: "2026-12-31", renewalNoticePeriod: 90, autoRenew: false, status: ContractStatus.Active },
    { id: "ct2", clientId: "c4", opportunityId: "opp-4", title: "Lattice Retail renewal agreement", contractValue: 740000, currency: "ZAR", startDate: "2026-01-15", endDate: "2026-12-31", renewalNoticePeriod: 60, autoRenew: true, status: ContractStatus.Active },
    { id: "ct3", clientId: "c6", opportunityId: "opp-6", title: "Marula rescue services agreement", contractValue: 560000, currency: "ZAR", startDate: "2026-02-01", endDate: "2026-08-31", renewalNoticePeriod: 30, autoRenew: false, status: ContractStatus.Draft },
  ],
  clients: [
    { id: "c1", name: "Boxfusion", industry: "Technology", clientType: 2, isActive: true, segment: "Enterprise" },
    { id: "c2", name: "Nexa Health", industry: "Healthcare", clientType: 2, isActive: true, segment: "Enterprise" },
    { id: "c3", name: "Umoya Logistics", industry: "Logistics", clientType: 2, isActive: true, segment: "Mid-market" },
    { id: "c4", name: "Lattice Retail", industry: "Retail", clientType: 2, isActive: true, segment: "Mid-market" },
    { id: "c5", name: "CrestBank", industry: "Financial Services", clientType: 2, isActive: true, segment: "Enterprise" },
    { id: "c6", name: "Marula Services", industry: "Professional Services", clientType: 2, isActive: true, segment: "SMB" },
  ],
  contacts: [
    { id: "cont1", clientId: "c1", firstName: "Dylan", lastName: "Meyer", email: "dylan@boxfusion.co.za", phoneNumber: "+27 11 111 2100", position: "Procurement Lead", isPrimaryContact: true },
    { id: "cont2", clientId: "c2", firstName: "Sanele", lastName: "Naicker", email: "sanele@nexahealth.com", phoneNumber: "+27 21 221 4400", position: "Programme Sponsor", isPrimaryContact: true },
    { id: "cont3", clientId: "c3", firstName: "Jabu", lastName: "Mkhize", email: "jabu@umoyalogistics.com", phoneNumber: "+27 31 410 9988", position: "Operations Director", isPrimaryContact: true },
    { id: "cont4", clientId: "c4", firstName: "Mia", lastName: "Steyn", email: "mia@latticeretail.com", phoneNumber: "+27 11 404 0192", position: "Commercial Manager", isPrimaryContact: true },
    { id: "cont5", clientId: "c5", firstName: "Kagiso", lastName: "Pieterse", email: "kagiso@crestbank.com", phoneNumber: "+27 12 765 4431", position: "Transformation Lead", isPrimaryContact: true },
    { id: "cont6", clientId: "c6", firstName: "Retha", lastName: "Pillay", email: "retha@marulaservices.com", phoneNumber: "+27 10 221 1008", position: "Head of Legal", isPrimaryContact: true },
  ],
  teamMembers: MOCK_TEAM_MEMBERS,
  automationFeed: [
    { id: "auto-1", title: "Lebo auto-assigned to Boxfusion renewal expansion", description: "Priority is high because the deal is worth R 1,850,000 and closes in 4 days.", createdAt: "2026-04-26T07:45:00Z" },
    { id: "auto-2", title: "Proposal sent deals moved to the Proposal Sent lane", description: "Nexa Health and Marula Services are visible in the correct kanban column.", createdAt: "2026-04-26T08:10:00Z" },
    { id: "auto-3", title: "Follow-up tasks generated for near-term deadlines", description: "Three next actions were scheduled for opportunities closing within 7 days.", createdAt: "2026-04-26T08:30:00Z" },
  ],
};
